Proyecto_Contabilidad/Controllers/AuthController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Proyecto_Contabilidad.Controllers
{
    public class AuthController : Controller
    {
        // GET: AuthController
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult RecoverPassword()
        {
            return View();
        }

        public ActionResult ChangePassword()
        {
            return View();
        }

        // GET: AuthController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AuthController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AuthController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AuthController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AuthController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AuthController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AuthController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Proyecto_Contabilidad/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Proyecto_Contabilidad.Models;
using System.Diagnostics;
using Proyecto_Contabilidad.Entities;

namespace Proyecto_Contabilidad.Controllers
{
    public class HomeController : Controller
    {

        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Principal()
        {
            return View();
        }

        public IActionResult Colaboradores()
        {
            return View();
        }

        public IActionResult Cliente()
        {
            return View();
        }
        public IActionResult Aprobacion()
        {
            return View();
        }
        public IActionResult Reportes()
        {
            return View();
        }

        public IActionResult Metricas()
        {
            return View();
        }
        public IActionResult Perfil()
        {
            return View();
        }

        public IActionResult Editar()
        {
            return View();
        }

        public IActionResult Editar2()
        {
            return View();
        }
              
        public IActionResult Repoprte1()
        {
            return View();
        }
     
        public IActionResult Nuevo3()
        {
            return View();
        }
  
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Proyecto_Contabilidad/Controllers/LogController.cs
using Microsoft.AspNetCore.Mvc;

namespace Proyecto_Contabilidad.Controllers
{
    public class LogController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Proyecto_Contabilidad/Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;

namespace Proyecto_Contabilidad.Controllers
{
    public class ReportController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Balance()
        {
            return View();
        }
    }
}

Proyecto_Contabilidad/Controllers/SeatController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Proyecto_Contabilidad.Controllers
{
    public class SeatController : Controller
    {
        // GET: SeatController
        public ActionResult Index()
        {
            return View();
        }
             
        public ActionResult List()
        {
            return View();
        }

        // GET: SeatController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SeatController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SeatController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SeatController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SeatController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SeatController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SeatController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult CreateDetail(int? id)
        {
            return View(id);
        }

    }
}

Proyecto_Contabilidad/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-name" content="mono" />

    <title>Mono - Responsive Admin & Dashboard Template</title>

    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Karla:400,700|Roboto" rel="stylesheet">
    <link href="~/plugins/material/css/materialdesignicons.min.css" rel="stylesheet" />
    <link href="~/plugins/simplebar/simplebar.css" rel="stylesheet" />

    <!-- PLUGINS CSS STYLE -->
    <link href="~/plugins/nprogress/nprogress.css" rel="stylesheet" />

    <link href="~/plugins/DataTables/DataTables-1.10.18/css/jquery.dataTables.min.css" rel="stylesheet" />

    <link href="~/plugins/jvectormap/jquery-jvectormap-2.0.3.css" rel="stylesheet" />

    <link href="~/plugins/daterangepicker/daterangepicker.css" rel="stylesheet" />

    <!-- MONO CSS -->
    <link id="main-css-href" rel="stylesheet" href="~/css/style.css" />

    <!-- FAVICON -->
    <link href="~/images/favicon.png" rel="shortcut icon" />

    <script src="~/plugins/nprogress/nprogress.js"></script>
</head>


<body class="navbar-fixed sidebar-fixed" id="body">
    <script>
        NProgress.configure({ showSpinner: false });
        NProgress.start();
    </script>

    <!-- ====================================
    ——— WRAPPER
    ===================================== -->
    <div class="wrapper">


        <!-- ====================================
          ——— LEFT SIDEBAR WITH OUT FOOTER
        ===================================== -->
        <aside class="left-sidebar sidebar-dark" id="left-sidebar">
            <div id="sidebar" class="sidebar sidebar-with-footer">
                <!-- Aplication Brand -->
                <div class="app-brand">
                    <a href="@Url.Action("Privacy", "Home")">
                        @* <img src="Images/Logo.png"> *@
                        <span class="brand-name">RG Advisory Group</span>


                    </a>
                </div>
                <!-- begin sidebar scrollbar -->
                <div class="sidebar-left" data-simplebar style="height: 100%;">
                    <!-- sidebar menu -->
                    <ul class="nav sidebar-inner" id="sidebar-menu">

                        <li class="active">
                            <a class="sidenav-item-link" href="@Url.Action("Privacy", "Home")">
                                <i class="mdi mdi-home-circle"></i>
                                <span class="nav-text">Principal</span>
                            </a>
                        </li>

                    </ul>

                </div>

                <div class="sidebar-footer">
                    <div class="sidebar-footer-content">
                    </div>
                </div>
            </div>
        </aside>



        <!-- ====================================
        ——— PAGE WRAPPER
        ===================================== -->
        <div class="page-wrapper" style="width:auto !important">

            <!-- Header -->
            <header class="main-header" id="header">
                <nav class="navbar navbar-expand-lg navbar-light" id="navbar">
                    <!-- Sidebar toggle button -->
                    <button id="sidebar-toggler" class="sidebar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                    </button>

                    <span class="page-title">AccountingSoft</span>

                    <div class="navbar-right ">
                    </div>

                    <ul class="nav navbar-nav">

                        <!-- User Account -->

                        <li class="dropdown-footer">
                            <a class="dropdown-link-item" onclick="logout()"> <i class="mdi mdi-logout"></i> Salir </a>
                        </li>
                    </ul>

                </nav>
            </header>
        </div>


        <!-- ====================================
        ——— CONTENT WRAPPER
        ===================================== -->
        <div class="content-wrapper">
            <!-- Top Statistics -->
            <br>
            <br>
            <br>
            <div class="card-header">
                <h1 class="mb-3" style="text-align:center">Bienvenido a AccountingSoft</h1>
                <br>
                <p style="text-align:center">Elige el cliente para iniciar</p>
            </div>
            <br>


            <div class="d-inline-block mb-1 d-flex justify-content-center">
                <div class="form-group">
                    <label for="mySelect">Cliente</label>
                    <select id="mySelect" class="mySelect form-select " style="width:auto !important" onchange="goToPrincipal()">
                        <option value="0">Seleccionar</option>
                    </select>
                </div>
            </div>

        </div>
    </div>

    <script src="~/plugins/jquery/jquery.min.js"></script>
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/plugins/simplebar/simplebar.min.js"></script>
    <script src="https://unpkg.com/hotkeys-js/dist/hotkeys.min.js"></script>


    <script src="~/js/mono.js"></script>
    <script src="~/js/chart.js"></script>
    <script src="~/js/map.js"></script>
    <script src="~/js/custom.js"></script>

    <script src="~/scripts/home.js"></script>

</body>
</html>

Proyecto_Contabilidad/Views/Home/Metricas.cshtml
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-name" content="mono" />

    <title>Mono - Responsive Admin & Dashboard Template</title>

    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Karla:400,700|Roboto" rel="stylesheet">
    <link href="~/plugins/material/css/materialdesignicons.min.css" rel="stylesheet" />
    <link href="~/plugins/simplebar/simplebar.css" rel="stylesheet" />

    <!-- PLUGINS CSS STYLE -->
    <link href="~/plugins/nprogress/nprogress.css" rel="stylesheet" />

    <link href="~/plugins/DataTables/DataTables-1.10.18/css/jquery.dataTables.min.css" rel="stylesheet" />

    <!-- MONO CSS -->
    <link id="main-css-href" rel="stylesheet" href="~/css/style.css" />

    <!-- FAVICON -->
    <link href="~/images/favicon.png" rel="shortcut icon" />

    <script src="~/plugins/nprogress/nprogress.js"></script>
</head>


<body class="navbar-fixed sidebar-fixed" id="body">
    <script>
        NProgress.configure({ showSpinner: false });
        NProgress.start();
    </script>

    <!-- ====================================
    ——— WRAPPER
    ===================================== -->
    <div class="wrapper">


        <!-- ====================================
          ——— LEFT SIDEBAR WITH OUT FOOTER
        ===================================== -->
        <aside class="left-sidebar sidebar-dark" id="left-sidebar">
            <div id="sidebar" class="sidebar sidebar-with-footer">
                <!-- Aplication Brand -->
                <div class="app-brand">
                    <a href="@Url.Action("Privacy", "Home")">
                        @* <img src="Images/Logo.png"> *@
                        <span class="brand-name">RG Advisory Group</span>


                    </a>
                </div>
                <!-- begin sidebar scrollbar -->
                <div class="sidebar-left" data-simplebar style="height: 100%;">
                    <!-- sidebar menu -->
                    <ul class="nav sidebar-inner" id="sidebar-menu">

                        <li>
                            <a class="sidenav-item-link" href="@Url.Action("Principal", "Home")">
                                <i class="mdi mdi-home-circle"></i>
                                <span class="nav-text">Principal</span>
                            </a>
                        </li>

                        <li>
                            <a class="sidenav-item-link" href="@Url.Action("List", "Employee")">
                                <i class="mdi mdi-briefcase-account-outline"></i>
                                <span class="nav-text">Colaboradores</span>
                            </a>
                        </li>

                        <li class="active">
                            <a class="sidenav-item-link" href="@Url.Action("Metricas", "Home")">
                                <i class="mdi mdi-chart-line"></i>
                                <span class="nav-text">Métricas</span>
                            </a>
                        </li>

                        <li class="section-title">
                            Funciones
                        </li>

                        <li>
                            <a class="sidenav-item-link" href="@Url.Action("List", "Customer")">
                                <i class="mdi mdi-account"></i>
                                <span class="nav-text">Clientes</span>
                            </a>
                        </li>

                        <li class="has-sub">
                            <a class="sidenav-item-link" href="javascript:void(0)" data-toggle="collapse" data-target="#email"
                               aria-expanded="false" aria-controls="email">

                                <i class="mdi mdi-square-edit-outline"></i>
                                <span class="nav-text">Asiento</span><b class="caret"></b>
                            </a>

                            <ul class="collapse sub-menu" id="email" data-parent="#sidebar-menu">

                                <li>
                                    <a class="sidenav-item-link" href="@Url.Action("Create", "Seat")">
                                        <span class="nav-text">Crear</span>

                                    </a>
                                </li>

                                <li>
                                    <a class="sidenav-item-link" href="@Url.Action("List", "Seat")">
                                        <span class="nav-text">Listar</span>

                                    </a>
                                </li>

                            </ul>

                        </li>

                        <li>
                            <a class="sidenav-item-link" href="@Url.Action("Reportes", "Home")">
                                <i class="mdi mdi-folder-outline"></i>
                                <span class="nav-text">Reportes</span>
                            </a>
                        </li>

                        <li>
                            <a class="sidenav-item-link" href="@Url.Action("Account", "Catalog")">
                                <i class="mdi mdi-file-multiple"></i>
                                <span class="nav-text">Catálogo De Cuentas</span>
                            </a>
                        </li>

                    </ul>

                </div>

                <div class="sidebar-footer">
                    <div class="sidebar-footer-content">
                    </div>
                </div>
            </div>
        </aside>



        <!-- ====================================
        ——— PAGE WRAPPER
        ===================================== -->
        <div class="page-wrapper">

            <!-- Header -->
            <header class="main-header" id="header">
                <nav class="navbar navbar-expand-lg navbar-light" id="navbar">
                    <!-- Sidebar toggle button -->
                    <button id="sidebar-toggler" class="sidebar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                    </button>

                    <span class="page-title">Métricas</span>

                    <div class="navbar-right ">
                    </div>

                    <ul class="nav navbar-nav">

                        <!-- User Account -->


                        <li class="dropdown-footer">
                            <a class="dropdown-link-item" href="@Url.Action("Index", "Auth")"> <i class="mdi mdi-logout"></i> Salir </a>
                        </li>
                    </ul>

                </nav>
            </header>


            <!-- ====================================
            ——— CONTENT WRAPPER
            ===================================== -->
            <div class="card card-default">
                <div class="card-header">
                    <h2>Historial</h2>


                </div>
                <div class="card-body">

                    <table id="productsTable" class="table table-hover table-product" style="width:100%">
                        <thead>
                            <tr>
                                <th>Usuario</th>
                                <th>Acción</th>
                                <th>Fecha</th>
                                <th>Hora</th>
                                <th></th>
                            </tr>
                        </thead>

                    </table>

                </div>

            </div>


            <!-- Footer -->
            <footer class="footer mt-auto">
                <div class="copyright bg-white">
                    <p>
                        &copy; <span id="copy-year"></span> Copyright RG Advisory Group
                    </p>
                </div>

            </footer>

        </div>
    </div>

    <script>
        var d = new Date();
        var year = d.getFullYear();
        document.getElementById("copy-year").innerHTML = year;
    </script>

    <script src="~/plugins/jquery/jquery.min.js"></script>
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/plugins/simplebar/simplebar.min.js"></script>
    <script src="https://unpkg.com/hotkeys-js/dist/hotkeys.min.js"></script>


    <script src="~/plugins/apexcharts/apexcharts.js"></script>

    <script src="~/plugins/DataTables/DataTables-1.10.18/js/jquery.dataTables.min.js"></script>

    <script src="~/plugins/daterangepicker/moment.min.js"></script>
    <script src="~/plugins/daterangepicker/daterangepicker.js"></script>

    <script>
        jQuery(document).ready(function () {
            jQuery('input[name="dateRange"]').daterangepicker({
                autoUpdateInput: false,
                singleDatePicker: true,
                locale: {
                    cancelLabel: 'Clear'
                }
            });
            jQuery('input[name="dateRange"]').on('apply.daterangepicker', function (ev, picker) {
                jQuery(this).val(picker.startDate.format('MM/DD/YYYY'));
            });
            jQuery('input[name="dateRange"]').on('cancel.daterangepicker', function (ev, picker) {
                jQuery(this).val('');
            });
        });
    </script>


</body>
</html>

Proyecto_Contabilidad/Views/Home/Principal.cshtml
@{
    ViewData["Title"] = "Principal";
}

<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-name" content="mono" />

    <title>Mono - Responsive Admin & Dashboard Template</title>

    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Karla:400,700|Roboto" rel="stylesheet">
    <link href="~/plugins/material/css/materialdesignicons.min.css" rel="stylesheet" />
    <link href="~/plugins/simplebar/simplebar.css" rel="stylesheet" />

    <!-- PLUGINS CSS STYLE -->
    <link href="~/plugins/nprogress/nprogress.css" rel="stylesheet" />

    <link href="~/plugins/DataTables/DataTables-1.10.18/css/jquery.dataTables.min.css" rel="stylesheet" />

    <link href="~/plugins/jvectormap/jquery-jvectormap-2.0.3.css" rel="stylesheet" />

    <link href="~/plugins/daterangepicker/daterangepicker.css" rel="stylesheet" />

    <!-- MONO CSS -->
    <link id="main-css-href" rel="stylesheet" href="~/css/style.css" />

    <!-- FAVICON -->
    <link href="~/images/favicon.png" rel="shortcut icon" />

    <script src="~/plugins/nprogress/nprogress.js"></script>
</head>


<body class="navbar-fixed sidebar-fixed" id="body">
    <script>
        NProgress.configure({ showSpinner: false });
        NProgress.start();
    </script>

    <!-- ====================================
    ——— WRAPPER
    ===================================== -->
    <div class="wrapper">


        <!-- ====================================
          ——— LEFT SIDEBAR WITH OUT FOOTER
        ===================================== -->
        <aside class="left-sidebar sidebar-dark" id="left-sidebar">
            <div id="sidebar" class="sidebar sidebar-with-footer">
                <!-- Aplication Brand -->
                <div class="app-brand">
                    <a href="@Url.Action("Privacy", "Home")">
                        @* <img src="Images/Logo.png"> *@
                        <span class="brand-name">RG Advisory Group</span>


                    </a>
                </div>
                <!-- begin sidebar scrollbar -->
                <div class="sidebar-left" data-simplebar style="height: 100%;">
                    <!-- sidebar menu -->
                    <ul class="nav sidebar-inner" id="sidebar-menu">

                        <li class="active">
                            <a class="sidenav-item-link" href="@Url.Action("Principal", "Home")">
                                <i class="mdi mdi-home-circle"></i>
                                <span class="nav-text">Principal</span>
                            </a>
                        </li>

                        <li>
                            <a class="sidenav-item-link" href="@Url.Action("List", "Employee")">
                                <i class="mdi mdi-briefcase-account-outline"></i>
                                <span class="nav-text">Colaboradores</span>
                            </a>
                        </li>

                        <li>
                            <a class="sidenav-item-link" href="@Url.Action("", "Log")">
                                <i class="mdi mdi-chart-line"></i>
                                <span class="nav-text">Métricas</span>
                            </a>
                        </li>

                        <li class="section-title">
                            Funciones
                        </li>

                        <li>
                            <a class="sidenav-item-link" href="@Url.Action("List", "Customer")">
                                <i class="mdi mdi-account"></i>
                                <span class="nav-text">Clientes</span>
                            </a>
                        </li>

                        <li class="has-sub">
                            <a class="sidenav-item-link" href="javascript:void(0)" data-toggle="collapse" data-target="#email"
                               aria-expanded="false" aria-controls="email">
                                <i class="mdi mdi-square-edit-outline"></i>
                                <span class="nav-text">Asiento</span><b class="caret"></b>
                            </a>

                            <ul class="collapse sub-menu" id="email"
                                data-parent="#sidebar-menu">

                                <li>
                                    <a class="sidenav-item-link" href="@Url.Action("Create", "Seat")">
                                        <span class="nav-text">Crear</span>

                                    </a>
                                </li>

                                <li>
                                    <a class="sidenav-item-link" href="@Url.Action("List", "Seat")">
                                        <span class="nav-text">Listar</span>

                                    </a>
                                </li>

                            </ul>
                        </li>

                        <li>
                            <a class="sidenav-item-link" href="@Url.Action("", "Report")">
                                <i class="mdi mdi-folder-outline"></i>
                                <span class="nav-text">Reportes</span>
                            </a>
                        </li>

                        <li>
                            <a class="sidenav-item-link" href="@Url.Action("Account", "Catalog")">
                                <i class="mdi mdi-file-multiple"></i>
                                <span class="nav-text">Catálogo De Cuentas</span>
                            </a>
                        </li>
                    </ul>

                </div>

                <div class="sidebar-footer">
                    <div class="sidebar-footer-content">
                    </div>
                </div>
            </div>
        </aside>



        <!-- ====================================
        ——— PAGE WRAPPER
        ===================================== -->
        <div class="page-wrapper" style="width:auto !important">

            <!-- Header -->
            <header class="main-header" id="header">
                <nav class="navbar navbar-expand-lg navbar-light" id="navbar">
                    <!-- Sidebar toggle button -->
                    <button id="sidebar-toggler" class="sidebar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                    </button>

                    <span class="page-title">AccountingSoft</span>

                    <div class="navbar-right ">
                        
                    </div>

                    <ul class="nav navbar-nav">

                        <!-- User Account -->

                        <li class="dropdown-footer">
                            <a class="dropdown-link-item" onclick="logout()"> <i class="mdi mdi-logout"></i> Salir </a>
                        </li>
                    </ul>

                </nav>
            </header>
        </div>


        <!-- ====================================
        ——— CONTENT WRAPPER
        ===================================== -->
        <div class="content-wrapper">
            <!-- Top Statistics -->
            <br>
            <br>
            <br>
            <div class="card-header">
                <h1 class="mb-3" style="text-align:center">Bienvenido a AccountingSoft</h1>
                <br>
                <strong id="customer-name" style="  display: flex; justify-content: center;"></strong>
            </div>

        </div>
    </div>

    <script src="~/plugins/jquery/jquery.min.js"></script>
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/plugins/simplebar/simplebar.min.js"></script>
    <script src="https://unpkg.com/hotkeys-js/dist/hotkeys.min.js"></script>


    <script src="~/js/mono.js"></script>
    <script src="~/js/chart.js"></script>
    <script src="~/js/map.js"></script>
    <script src="~/js/custom.js"></script>

    <script src="~/scripts/principal.js"></script>
</body>
</html>